export const APPROVAL_WIDGET_URI = 'ui://numtema/approval.html';

export function renderApprovalWidget(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#172019;background:transparent}*{box-sizing:border-box}body{margin:0;padding:12px}.card{border:1px solid rgba(59,83,67,.18);border-radius:24px;background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(239,245,240,.96));box-shadow:0 18px 48px rgba(23,48,34,.12);padding:22px}.row{display:flex;align-items:center;gap:12px}.shield{width:44px;height:44px;border-radius:15px;background:#173f32;color:white;display:grid;place-items:center;font-weight:900}h2{font-size:20px;margin:0}.muted{color:#647067;line-height:1.5}.facts{display:grid;gap:8px;margin:16px 0;padding:14px;border-radius:16px;background:rgba(255,255,255,.72)}.fact{display:flex;justify-content:space-between;gap:16px;font-size:13px}.fact b{word-break:break-word;text-align:right}.actions{display:flex;gap:10px;margin-top:18px}button{border:0;border-radius:14px;padding:12px 16px;font:inherit;font-weight:750;cursor:pointer}.approve{background:#173f32;color:white}.deny{background:#e6ece8;color:#28382f}.status{font-size:13px;margin-top:12px;color:#536157}
</style></head><body><section class="card"><div class="row"><div class="shield">✓</div><div><h2>Secure approval required</h2><div class="muted">Review the exact action before it is executed.</div></div></div><div class="facts"><div class="fact"><span>Tool</span><b id="tool">—</b></div><div class="fact"><span>Risk</span><b id="risk">—</b></div><div class="fact"><span>Expires</span><b id="expires">—</b></div></div><div class="actions"><button class="approve" id="approve">Approve and run</button><button class="deny" id="deny">Deny</button></div><div class="status" id="status"></div></section><script>
const output=window.openai?.toolOutput||{};const input=window.openai?.toolInput||{};
const challenge=output.challenge_id;const target=output.target_tool;const args=output.arguments||input.arguments||{};
document.getElementById('tool').textContent=target||'Unknown';document.getElementById('risk').textContent=output.risk_class||'Governed';document.getElementById('expires').textContent=output.expires_at||'—';
async function decide(decision){const status=document.getElementById('status');status.textContent=decision==='approve'?'Confirming approval…':'Denying…';try{const result=await window.openai.callTool('foundry_approval_confirm',{challenge_id:challenge,decision});if(decision==='approve'&&!result?.isError){status.textContent='Approved. Executing exact action…';const executed=await window.openai.callTool(target,args);status.textContent=executed?.isError?'Execution returned an error.':'Action completed.';}else status.textContent=decision==='approve'?'Approval failed.':'Action denied.';}catch(error){status.textContent='Approval could not be completed.';}}
document.getElementById('approve').onclick=()=>decide('approve');document.getElementById('deny').onclick=()=>decide('deny');
</script></body></html>`;
}
