import type { ToolContract } from '../contracts/types.js';
import type { ToolArgumentClassification, ToolArgumentClass } from './types.js';

type Schema = Record<string, unknown>;

export function classifyToolArguments(tool: ToolContract): ToolArgumentClassification[] {
  const schema = tool.input_schema as Schema;
  const properties = objectValue(schema.properties);
  const required = new Set(arrayValue(schema.required).filter((value): value is string => typeof value === 'string'));
  const locations = parameterLocations(tool);
  return Object.keys(properties).sort().map((name) => {
    const location = locations.get(name);
    const classification = classifyName(name, location);
    return { name, classification, reason: classificationReason(classification), ...(location === undefined ? {} : { location }), required: required.has(name) };
  });
}

export function buildModelInputSchema(tool: ToolContract, classifications = classifyToolArguments(tool)): Schema {
  const source = structuredClone(tool.input_schema) as Schema;
  const properties = objectValue(source.properties);
  const visible = new Set(classifications.filter((item) => item.classification === 'model_argument').map((item) => item.name));
  const filtered: Schema = {};
  for (const [name, value] of Object.entries(properties)) {
    if (visible.has(name)) filtered[name] = enrichPropertyDescription(name, structuredClone(value) as Schema);
  }
  source.properties = filtered;
  source.required = arrayValue(source.required).filter((name) => typeof name === 'string' && visible.has(name));
  source.additionalProperties = false;
  return source;
}

function classifyName(name: string, location?: string): ToolArgumentClass {
  const normalized = name.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (location === 'cookie' || /authorization|apikey|accesstoken|clientsecret|password|credential/.test(normalized)) return 'credential_managed';
  if (/traceid|requestid|correlationid|idempotencykey|nonce/.test(normalized)) return 'runtime_managed';
  if (/^x[a-z0-9]+/.test(normalized) && location === 'header') return 'runtime_managed';
  if (/signature|webhooksecret/.test(normalized)) return 'hidden_internal';
  return 'model_argument';
}

function classificationReason(value: ToolArgumentClass): string {
  return ({
    model_argument: 'Business input that the model may choose from the user request.',
    runtime_managed: 'Transport or safety value generated by the runtime.',
    credential_managed: 'Credential material resolved only at the execution boundary.',
    server_default: 'Safe fixed value supplied by the provider or project configuration.',
    hidden_internal: 'Internal transport field that must not be exposed to the model.'
  })[value];
}

function parameterLocations(tool: ToolContract): Map<string, string> {
  const foundry = objectValue(objectValue(tool.extensions).foundry);
  const parameters = Array.isArray(foundry.parameter_contract) ? foundry.parameter_contract : [];
  const map = new Map<string, string>();
  for (const item of parameters) {
    const entry = objectValue(item);
    if (typeof entry.name === 'string' && typeof entry.location === 'string') map.set(entry.name, entry.location);
  }
  return map;
}

function enrichPropertyDescription(name: string, schema: Schema): Schema {
  if (typeof schema.description !== 'string' || schema.description.trim().length === 0) schema.description = inferPropertyDescription(name, schema);
  const properties = objectValue(schema.properties);
  if (Object.keys(properties).length > 0) {
    const enriched: Schema = {};
    for (const [child, value] of Object.entries(properties)) enriched[child] = enrichPropertyDescription(child, structuredClone(value) as Schema);
    schema.properties = enriched;
  }
  if (schema.items && typeof schema.items === 'object') schema.items = enrichPropertyDescription(`${name} item`, structuredClone(schema.items) as Schema);
  return schema;
}

function inferPropertyDescription(name: string, schema: Schema): string {
  const words = name.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[_-]+/g, ' ').toLowerCase();
  if (schema.format === 'uuid') return `Unique identifier for the ${words.replace(/ id$/, '')}.`;
  if (schema.format === 'email') return `Email address for ${words === 'email' ? 'the resource' : words}.`;
  if (/cursor/i.test(name)) return 'Pagination cursor returned by a previous list request.';
  if (/limit|pageSize/i.test(name)) return 'Maximum number of records to return.';
  if (/expand|include/i.test(name)) return 'Optional related resources to include in the response.';
  return `Value for ${words}.`;
}

function objectValue(value: unknown): Schema { return value && typeof value === 'object' && !Array.isArray(value) ? value as Schema : {}; }
function arrayValue(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
